name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+' # <major>.<minor>.<patch>
    - '[0-9]+.[0-9]+.[0-9]+-[a-z]+' # <major>.<minor>.<patch>-<name>
    - '[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+' # <major>.<minor>.<patch>-<name>.<id>
    - '!0[0-9]+.*' # only 0 or positive integers in <major>
    - '!*.0[0-9]+*' # only 0 or positive integers in <minor>, <patch> and <id>

env:
  regex: ((0|[1-9][0-9]*)\.){2}(0|[1-9][0-9]*)(-[a-z]+(\.(0|[1-9][0-9]*))?)?
  sha: ${{ github.sha }}
  name: ${{ github.ref_name }}

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout code
      id: checkout
      uses: actions/checkout@v3

    - name: Fetch all tags
      run: git fetch --prune --unshallow --tags

    - name: Get previous release
      run: echo "prev=$(git -c 'versionsort.suffix=-' tag --sort=-v:refname --no-contains "$sha" | grep -E -o -m 1 "$regex" | head -1)" >> $GITHUB_ENV

    - name: Get commits list
      run: |
        git log "$prev".."$sha" --pretty=format:"[\`%h\`](../../commit/%H) %s" > commits
        [ ! -s commits ] \
        && echo "Error: no new commits since '$prev'" 1>&2 \
        && exit 1
        echo >> commits

    - name: Generate body
      run: .github/scripts/body.sh > body.md

    - name: Append changelog link to body
      run: |
        echo "**Full Changelog**: [\`$prev..$name\`](../../compare/$prev..$name)" >> body.md

    - name: Release on GitHub
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        commitish: ${{ github.sha }} # you may want to update files
        release_name: ${{ github.ref_name }}
        body_path: body.md
        # '-' appears only if a pre-release suffix is present
        prerelease: ${{ contains(github.ref_name, '-') }}
        draft: true
